UsedVehicleSystem/Models/Ilan.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UsedVehicleSystem.Models
{
    public class Ilan
    {
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string ilanAdi { get; set; }

        [ForeignKey("AracSaticisi")]
        public int aracSaticisiID { get; set; }

        [NotMapped]
		public AracSaticisi aracSaticisi { get; set; }

        [ForeignKey("Arac")]
        public int ilandakiAracID { get; set; }

        [NotMapped]
		public Arac ilandakiArac { get; set; }
        public double ilanFiyati { get; set; }

        [NotMapped]
        public List<string> imgSrcs { get; set; }
        public bool yayindaMi { get; set; }
        public bool onayliMi { get; set; }
    }
}

UsedVehicleSystem/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using UsedVehicleSystem.Models;
using UsedVehicleSystem.Repository;
using UsedVehicleSystem.Services;

namespace UsedVehicleSystem.Controllers
{
	public class HomeController : Controller
	{
		private IUyeYonetimi _uyeYonetimi;

        public HomeController(IUyeYonetimi uyeYonetimi)
		{
            _uyeYonetimi = uyeYonetimi;
        }

        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("SessionID") != null)
            {
                int sessionID = int.Parse(HttpContext.Session.GetString("SessionID"));
                Uye uye = _uyeYonetimi.UyeGetir(sessionID);
                ViewBag.Uye = uye;
                ViewBag.MusteriMi = _uyeYonetimi.MusteriMi(uye.ID); 
            }
            return View();
        }

        public IActionResult Home()
        {
            return RedirectToAction("Index");
        }
	}
}

UsedVehicleSystem/Controllers/IlanController.cs
using Microsoft.AspNetCore.Mvc;
using UsedVehicleSystem.Models;
using UsedVehicleSystem.Services;
using UsedVehicleSystem.Mediator;
using UsedVehicleSystem.Facade;

namespace UsedVehicleSystem.Controllers
{
	public class IlanController : Controller
	{
        IFacade _facade;
        IIlanYonetimi _ilanYonetimi;

        public IlanController(IIlanYonetimi ilanYonetimi, IFacade facade)
		{
			_ilanYonetimi = ilanYonetimi;
            _facade = facade;
        }

        private AracSaticisi AktifAracSaticisiniGetir()
        {
            if (HttpContext.Session.GetString("SessionID") == null)
            {
                return null;
            }
            else
            {
                int ID = int.Parse(HttpContext.Session.GetString("SessionID"));
                return _facade.AracSaticisiGetir(ID);
            }
        }

        public IActionResult IlanEkle()
		{
            AracSaticisi aracSaticisi = AktifAracSaticisiniGetir();

            if (aracSaticisi == null)
            {
                return RedirectToAction("Index", "Home");
            }

            ViewBag.Markalar = _facade.AracTumMarkaGetir();
            ViewBag.Modeller = _facade.AracTumModelGetir();
            ViewBag.AracSaticisi = aracSaticisi;

            return View();
		}

		[HttpPost]
		public IActionResult IlanEkle(Ilan ilan, int kilometre, string aracMarkasiID, string aracModelID, string? AracDonanimlari = "")
        {
            AracSaticisi aracSaticisi = AktifAracSaticisiniGetir();
            if (aracSaticisi == null)
                return RedirectToAction("Index", "Home");

            ilan.aracSaticisiID = aracSaticisi.ID;
            ilan.aracSaticisi = aracSaticisi;

            Arac ilandakiArac = new Arac();
            ilandakiArac.kilometre = kilometre;
            ilandakiArac.aracMarkasiID = int.Parse(aracMarkasiID);
            ilandakiArac.aracMarkasi = _facade.AracMarkaGetir(int.Parse(aracMarkasiID));
            ilandakiArac.aracModeliID = int.Parse(aracModelID);
            ilandakiArac.aracModeli = _facade.AracModelGetir(int.Parse(aracModelID));

            //ilandaki aracı kaydet
            _facade.AracEkle(ilandakiArac);
            ViewBag.AracSaticisi = aracSaticisi;
            ViewBag.Ilan = _facade.IlanEkle(ilan, ilandakiArac, aracSaticisi, AracDonanimlari); ;
            return RedirectToAction("Ilanlarim");
		}

        [HttpPost]
        public IActionResult IlanGuncelle(Ilan ilan, int kilometre, string aracMarkasiID, string aracModelID)
        {
            AracSaticisi aracSaticisi = AktifAracSaticisiniGetir();
            if (aracSaticisi == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                _ilanYonetimi.IlanGuncelle(ilan.ID, ilan);
                return RedirectToAction("Ilanlarim");
            }
        }

		public IActionResult Ilanlar() 
        {
            List<Ilan> ilanlar = _facade.TumIlanlariGetir();

            if(_facade.AracTumMarkaGetir() != null)
                ViewBag.Markalar = _facade.AracTumMarkaGetir();
            else
                ViewBag.Markalar = new List<AracMarkasi>();

            if (_facade.AracTumModelGetir() != null)
                ViewBag.Modeller = _facade.AracTumModelGetir();
            else
                ViewBag.Modeller = new List<AracMarkasi>();

            return View(ilanlar);
        }

        public IActionResult Ilanlarim()
        {
            AracSaticisi aracSaticisi = AktifAracSaticisiniGetir();
            if (aracSaticisi == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                List<Ilan> ilanlarim = _facade.IlanlariListele(aracSaticisi);
                return View(ilanlarim);
            }
        }
		
		public IActionResult IlanSil(int ID)
        {
            AracSaticisi aracSaticisi = AktifAracSaticisiniGetir();
            if (aracSaticisi == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                _facade.AracSil(_ilanYonetimi.IlanGetir(ID).ilandakiAracID);
                _ilanYonetimi.IlanSil(ID);
                return RedirectToAction("Ilanlarim");
            }
		}

        public IActionResult IlanArama(Ilan ilan, string? Sanziman, string? AracTuru, string? UretimYili, string? YakitTuru, string? MotorTuru, string? Marka, string? Model)
        {
            ilan.ilandakiArac = new Arac
            {
                aracMarkasi = new AracMarkasi { ID = int.Parse(Marka ?? "0") },
                aracModeli = new AracModeli
                {
                    ID = int.Parse(Model ?? "0"),
                    sanziman = Sanziman ?? "",
                    aracTuru = AracTuru ?? "",
                    uretimYili = int.Parse(UretimYili ?? "0"),
                    yakitTuru = YakitTuru ?? "",
                    motorTuru = MotorTuru ?? ""
                }
            };

            List<Ilan> ilanlar = _ilanYonetimi.IlanAra(ilan);


            ViewBag.Filtre = ilan;
            ViewBag.Ilanlar = ilanlar;

            return View();
        }

		public IActionResult IlanGoruntule(int ID)
        {
            ViewBag.CanIEdit = false;
            ViewBag.Uye = _facade.UyeGetir(int.Parse(HttpContext.Session.GetString("SessionID")));

            AracSaticisi aracSaticisi = AktifAracSaticisiniGetir();

            Ilan ilan = _ilanYonetimi.IlanGetir(ID);

            List<Yorum> aracSaticisinaYorumlar = _facade.TumYorumlariGetir(ilan.aracSaticisiID);
            ViewBag.SaticiyaYapilanYorumar = aracSaticisinaYorumlar;
            if (ilan == null)
                return RedirectToAction("Index", "Home");
            if (aracSaticisi != null)
            {
                ViewBag.CanIEdit = true;
            }

            if (_facade.AracTumMarkaGetir() != null)
                ViewBag.Markalar = _facade.AracTumMarkaGetir();
            else
                ViewBag.Markalar = new List<AracMarkasi>();

            if (_facade.AracTumModelGetir() != null)
                ViewBag.Modeller = _facade.AracTumModelGetir();
            else
                ViewBag.Modeller = new List<AracModeli>();

            return View(ilan);
		}

        [HttpPost]
        public IActionResult YorumYap(Yorum yorum)
        {
            _facade.YorumEkle(yorum.AracSaticisiID, yorum.yorumIcerigi, yorum.musteriAdi);
            return RedirectToAction("Ilanlar");
        }

        public IActionResult IlanKarsilastir(int ilanID1, int ilanID2)
        {
            Ilan ilan1 = _facade.IlanGetir(ilanID1);
            Ilan ilan2 = _facade.IlanGetir(ilanID2);

            ViewBag.Ilan1 = ilan1;
            ViewBag.Ilan2 = ilan2;

            return View();
		}

	}
}

UsedVehicleSystem/Controllers/UyeController.cs
using Microsoft.AspNetCore.Mvc;
using UsedVehicleSystem.Models;
using UsedVehicleSystem.Services;

namespace UsedVehicleSystem.Controllers
{
	public class UyeController : Controller
	{
        IUyeYonetimi _uyeYonetimi;

        public UyeController(IUyeYonetimi uyeYonetimi)
        {
            _uyeYonetimi = uyeYonetimi;
        }

        public IActionResult Giris()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GirisYap(string Eposta, string Sifre)
        {
            if(Eposta == null || Sifre == null) 
            {
                ViewBag.Hata = "Giriş alanları bos birakilamaz.";
                return View("Giris");
            }

            Uye girisYapilan = _uyeYonetimi.GirisYap(Eposta, Sifre);
            if(girisYapilan == null)
            {
                ViewBag.Hata = "Giriş alanları yanlış.";
                return View("Giris");
            }
            else
            {
                HttpContext.Session.SetString("SessionID", girisYapilan.ID.ToString());
                return RedirectToAction("Profil");
            }
        }

        public IActionResult Kayit()
        {
            return View();
        }

        [HttpPost]
        public IActionResult KayitOl(Uye kayitlanacakUye, string uyelikTuru, string? telefonNumarasi = null)
        {
            if(kayitlanacakUye.ad == null || kayitlanacakUye.soyad == null || kayitlanacakUye.eposta == null || kayitlanacakUye.sifre == null  || uyelikTuru == null)
            {
                ViewBag.Hata = "Boş alan bırakamazsınız. ";
                return View("Kayit");
            }
            if (_uyeYonetimi.UyeVarMi(kayitlanacakUye.eposta))
            {
                ViewBag.Hata = "Eposta hesabı önceden kullanılmış mevcut.";
                return View("Kayit");
            }

            bool musteriMi = uyelikTuru.ToUpperInvariant().ToString() == ("1").ToUpperInvariant() ? true : false;

            Uye kayit = null;

            if (musteriMi)
            {
                kayit = _uyeYonetimi.UyeOl(kayitlanacakUye);
            }
            else
            {
                string telNo;
                if (telefonNumarasi != null)
                    telNo = telefonNumarasi;
                else
                    telNo = "1111111111";

                kayit = _uyeYonetimi.UyeOl(kayitlanacakUye, telNo);
            }

            HttpContext.Session.SetString("SessionID", kayit.ID.ToString());
            return RedirectToAction("Profil");
        }

        public IActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }


        public IActionResult Home()
        {
            if(HttpContext.Session.GetString("SessionID") == null)
            {
                return View("Giris");
            }

            Uye gonderilecekUye = _uyeYonetimi.UyeGetir(int.Parse(HttpContext.Session.GetString("SessionID")));

            if(gonderilecekUye == null)
            {
                HttpContext.Session.Remove("SessionID");
                ViewBag.Hata = "Giriş bilgileri hatalı. Lütfen tekrar deneyin.";
                return View("Giris");
            }

            ViewBag.Uye = gonderilecekUye;
            ViewBag.AracSaticisiMi = !_uyeYonetimi.MusteriMi(int.Parse(HttpContext.Session.GetString("SessionID")));

            return RedirectToAction("Index", "Home");
        }

        public IActionResult Cikis()
        {
            HttpContext.Session.Remove("SessionID");
            return RedirectToAction("Home");
        }

        public IActionResult Profil()
        {
            Uye uye;
            if (HttpContext.Session.GetString("SessionID") != null)
            {
                uye = _uyeYonetimi.UyeGetir(int.Parse(HttpContext.Session.GetString("SessionID")));
            }
            else
            {
                return RedirectToAction("Index");
            }
            return View(uye);
        }
    }
}

UsedVehicleSystem/Views/Home/Ilan.cshtml
<div class="ilanSayfasi">
    <div class="row mt-3">
        <div class="col-12">
            <div class="card">
                <div class="card-body vertical-center">
                    <h3 class="text-center">İlan Başlığı</h3>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-md-4">
            <div class="card h-100">
                <div class="card-body">
                    <div class="row">
                        <div class="col">
                            <img src="1.jpg" alt="Profil Fotoğrafı" class="img-fluid rounded-corners">
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col">
                            <img src="1.jpg" alt="Fotoğraf 1" class="img-fluid">
                        </div>
                        <div class="col">
                            <img src="2.jpg" alt="Fotoğraf 2" class="img-fluid">
                        </div>
                        <div class="col">
                            <img src="3.jpg" alt="Fotoğraf 3" class="img-fluid">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card h-100">
                <div class="card-body">
                    <table class="table">
                        <tbody>
                            <tr>
                                <td>Araç Adı</td>
                                <td>Örnek Araç</td>
                            </tr>
                            <tr>
                                <td>Üretim Yılı</td>
                                <td>2010</td>
                            </tr>
                            <tr>
                                <td>Diğer</td>
                                <td>Yakında</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card h-100">
                <div class="card-body">
                    <table class="table">
                        <tbody>
                            <tr>
                                <td>Satıcı:</td>
                                <td>Ahmet</td>
                            </tr>
                            <tr>
                                <td>İlan Fiyatı:</td>
                                <td>1000</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    Hello World
                </div>
            </div>
        </div>
    </div>
</div>

UsedVehicleSystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    var uye = (Uye)ViewBag.Uye;
}
@if (uye == null)
{
    <div class="text-center">
        <p>Sizde ilanları görüntülemek, satın almak veya kendi aracınızı satmak için Üye olarak giriş yapın.</p>
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <div class="d-grid gap-3 mb-3">
                            <a asp-controller="Uye" asp-action="Giris" class="btn btn-primary btn-lg" id="loginButton">Giriş Yap</a>
                            <a asp-controller="Uye" asp-action="Kayit" class="btn btn-primary btn-lg" id="registerButton">Kayıt Ol</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
else
{
    <div class="text-center">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <div class="d-grid gap-3 mb-3">
                            <a asp-controller="Uye" asp-action="Home" class="btn btn-primary btn-lg " id="userHome">Ana Sayfanız</a>
                            <a asp-controller="Uye" asp-action="Profil" class="btn btn-primary btn-lg " id="profil">Profil</a>
                            @if (ViewBag.MusteriMi != null && ViewBag.MusteriMi == false)
                            {
                                <a asp-controller="Ilan" asp-action="Ilanlarim" class="btn btn-primary btn-lg " id="profil">İlanlarım</a>
                                <a asp-controller="Ilan" asp-action="IlanEkle" class="btn btn-primary btn-lg " id="profil">Ilan Ekle</a>
                            }
                            <a asp-controller="Ilan" asp-action="Ilanlar" class="btn btn-primary btn-lg " id="userHome">Vitrin</a>
                            <a asp-controller="Uye" asp-action="Cikis" class="btn btn-danger btn-lg " id="userHome">Çıkış Yap</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}


UsedVehicleSystem/Views/Home/SearchResultPage.cshtml
<div class="aramaSonuclariSayfasi">
    <div class="card my-4">
        <div class="card-body">
            <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder="Ara">
                <button class="btn btn-primary" type="button">Ara</button>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Örnek Menü</h5>
                    <ul class="list-group">
                        <li class="list-group-item">Öğe 1</li>
                        <li class="list-group-item">Öğe 2</li>
                        <li class="list-group-item">Öğe 3</li>
                        <li class="list-group-item">Öğe 4</li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-8">
            <div class="card">
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Başlık</th>
                                <th scope="col">Açıklama</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row">1</th>
                                <td>İlan 1</td>
                                <td>İlan 1 açıklama</td>
                            </tr>
                            <tr>
                                <th scope="row">2</th>
                                <td>İlan 2</td>
                                <td>İlan 2 açıklama</td>
                            </tr>
                            <!-- Diğer ilanlar -->
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="card my-4">
        <div class="card-body">
            <nav aria-label="Pagination">
                <ul class="pagination justify-content-center">
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Önceki</a>
                    </li>
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="#">1 <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Sonraki</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>