UsedVehicleSystem/Models/SistemYoneticisi.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UsedVehicleSystem.Models
{
    public class SistemYoneticisi
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        [Required]
        public string takmaAd { get; set; }

        [Required]
        public string sifre { get; set; }
    }
}

UsedVehicleSystem/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using UsedVehicleSystem.Models;
using UsedVehicleSystem.Repository;
using UsedVehicleSystem.Services;

namespace UsedVehicleSystem.Controllers
{
	public class HomeController : Controller
	{
		private IUyeYonetimi _uyeYonetimi;

        public HomeController(IUyeYonetimi uyeYonetimi)
		{
            _uyeYonetimi = uyeYonetimi;
        }

        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("SessionID") != null)
            {
                int sessionID = int.Parse(HttpContext.Session.GetString("SessionID"));
                Uye uye = _uyeYonetimi.UyeGetir(sessionID);
                ViewBag.Uye = uye;
                ViewBag.MusteriMi = _uyeYonetimi.MusteriMi(uye.ID); 
            }
            return View();
        }

        public IActionResult Home()
        {
            return RedirectToAction("Index");
        }
	}
}

UsedVehicleSystem/Controllers/SistemYoneticisiController.cs
using Microsoft.AspNetCore.Mvc;
using UsedVehicleSystem.Models;
using UsedVehicleSystem.Services;

namespace UsedVehicleSystem.Controllers
{
    public class SistemYoneticisiController : Controller
    {
        ISistemYonetimi _sistemYonetimi;

        public SistemYoneticisiController(ISistemYonetimi sistemYonetimi)
        {
            _sistemYonetimi = sistemYonetimi;
        }

        public SistemYoneticisi? SistemYoneticisiGetir()
        {
            if (HttpContext.Session.GetString("systemID") == null)
            {
                return null;
            }
            else
            {
                int ID = int.Parse(HttpContext.Session.GetString("systemID") ?? "-1");
                return _sistemYonetimi.YoneticiGetir(ID);
            }
        }

        public IActionResult Index()
        {
            return RedirectToAction("Home");
        }

        public IActionResult Home()
        {
            SistemYoneticisi yonetici = SistemYoneticisiGetir();
            if (yonetici != null)
                return View(yonetici);
            else
                return RedirectToAction("Giris");
        }

        public IActionResult Giris()
        {
            if (SistemYoneticisiGetir() != null)
                return RedirectToAction("Home");
            else
                return View();
        }

        [HttpPost]
        public IActionResult GirisYap(SistemYoneticisi sy)
        {
            if (SistemYoneticisiGetir() != null)
                return RedirectToAction("Home");
            else
            {
                SistemYoneticisi yonetici = _sistemYonetimi.GirisYap(sy.takmaAd, sy.sifre);
                if(yonetici == null)
                {
                    ViewBag.Hata = "Giriş bilgileri yanlış.";
                    return View("Giris");
                }
                else
                {
                    HttpContext.Session.SetString("systemID", yonetici.ID.ToString());
                    return RedirectToAction("Home");
                }
            }
        }

        public IActionResult Ilanlar()
        {
            List<Ilan> ilanlar = _sistemYonetimi.TumIlanlariGetir();
            return View(ilanlar);
        }

        public IActionResult IlanOnayla(int ID)
        {
            _sistemYonetimi.IlanOnayla(ID);
            return RedirectToAction("Ilanlar");
        }

        public IActionResult Cikis()
        {
            if (SistemYoneticisiGetir() != null)
                HttpContext.Session.Remove("systemID");

            return RedirectToAction("Home");
        }

        public IActionResult AracMarkaEkle()
        {
            ViewBag.Markalar = _sistemYonetimi.TumAracMarkalariniGetir();
            return View();
        }

        [HttpPost]
        public IActionResult AracMarkaEkle(AracMarkasi marka)
        {
            SistemYoneticisi yonetici = SistemYoneticisiGetir();
            if (yonetici == null)
                return RedirectToAction("Home");

            ViewBag.Markalar = _sistemYonetimi.TumAracMarkalariniGetir();

            if (_sistemYonetimi.AracMarkaEkle(marka) == false)
                ViewBag.Hata = "Daha önce var olan markayı ekleyemezsiniz.";
            else
                ViewBag.AracMarka = marka;

            return View();
        }

        public IActionResult AracModelEkle()
        {
            ViewBag.Modeller = _sistemYonetimi.TumAracModelleriniGetir();
            return View();
        }

        [HttpPost]
        public IActionResult AracModelEkle(AracModeli model)
        {
            SistemYoneticisi yonetici = SistemYoneticisiGetir();
            if (yonetici == null)
                return RedirectToAction("Home");

            ViewBag.Modeller = _sistemYonetimi.TumAracModelleriniGetir();

            if(_sistemYonetimi.AracModelEkle(model) == false)
                ViewBag.Hata = "Daha önce var olan modeli ekleyemezsiniz.";
            else
                ViewBag.AracModel = model;

            return View();
        }

    }
}

UsedVehicleSystem/Views/SistemYoneticisi/AracMarkaEkle.cshtml
@if (ViewBag.AracMarka != null)
{
    var aracMarka = (AracMarkasi)@ViewBag.AracMarka;

    <div class="alert alert-info">
        <b>Başarıyla Eklendi</b>
        <p>@aracMarka.markaAdi</p>
    </div>
}

@if(ViewBag.Hata != null)
{
    @if(ViewBag.Hata != "")
    {
        <div class="alert alert-danger">
            @ViewBag.Hata
        </div>
    }
}

<div class="container">
    <h1>Araç Marka Ekle</h1>
    <form asp-controller="SistemYoneticisi" asp-action="AracMarkaEkle">
        <div class="form-group">
            <label for="modelAdi">Marka Adı:</label>
            <input type="text" class="form-control" id="markaAdi" name="markaAdi">
        </div>
        <button type="submit" class="btn btn-primary">Ekle</button>
    </form>
</div>

@{
    var Markalar = (List<AracMarkasi>)ViewBag.Markalar ?? new List<AracMarkasi>() { };
}

<div class="container">
    <table class="table">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Marka Adı</th>
    </tr>
    </thead>
    <tbody>
        @foreach(var Marka in Markalar){
            <tr>
                <td scope="col">@Marka.ID</td>
                <td scope="col">@Marka.markaAdi</td>
            </tr>
        }
    </tbody>
</table>
</div>

UsedVehicleSystem/Views/SistemYoneticisi/AracModelEkle.cshtml
@if (ViewBag.AracModel != null)
{
    var aracModel = (AracModeli)@ViewBag.AracModel;
        <div class="alert alert-info">
            <b>İşlem Başarılı</b>
            <p>
                @aracModel.modelAdi başarıyla eklendi.
            </p>
        </div>
}

@if(ViewBag.Hata != null){
    @if(ViewBag.Hata != ""){
        <div class="alert alert-danger">
            @ViewBag.Hata
        </div>
    }
}

<div class="container">
    <h1>Araç Modeli Ekle</h1>
    <form asp-controller="SistemYoneticisi" asp-action="AracModelEkle">
        <div class="form-group">
            <label for="modelAdi">Model Adı:</label>
            <input type="text" class="form-control" id="modelAdi" name="modelAdi">
        </div>
        <div class="form-group">
            <label for="sanziman">Şanzıman:</label>
            <input type="text" class="form-control" id="sanziman" name="sanziman">
        </div>
        <div class="form-group">
            <label for="yakitTuru">Yakıt Türü:</label>
            <input type="text" class="form-control" id="yakitTuru" name="yakitTuru">
        </div>
        <div class="form-group">
            <label for="motorTuru">Motor Türü:</label>
            <input type="text" class="form-control" id="motorTuru" name="motorTuru">
        </div>
        <div class="form-group">
            <label for="uretimYili">Üretim Yılı:</label>
            <input type="number" class="form-control" id="uretimYili" name="uretimYili">
        </div>
        <div class="form-group">
            <label for="aracTuru">Araç Türü:</label>
            <input type="text" class="form-control" id="aracTuru" name="aracTuru">
        </div>
        <button type="submit" class="btn btn-primary">Ekle</button>
    </form>
</div>

@{
    var Modeller = (List<AracModeli>)ViewBag.Modeller ?? new List<AracModeli>() { };
}

<div class="container">
    <table class="table">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Model Adı</th>
        <th scope="col">Araç Türü</th>
        <th scope="col">Motor Türü</th>
        <th scope="col">Yakıt Türü</th>
        <th scope="col">Şanzıman</th>
        <th scope="col">Üretim Yılı</th>
    </tr>
    </thead>
    <tbody>
        @foreach(var Model in Modeller){
            <tr>
                <td scope="col">@Model.ID</td>
                <td scope="col">@Model.modelAdi</td>
                <td scope="col">@Model.aracTuru</td>
                <td scope="col">@Model.motorTuru</td>
                <td scope="col">@Model.yakitTuru</td>
                <td scope="col">@Model.sanziman</td>
                <td scope="col">@Model.uretimYili</td>
            </tr>
        }
    </tbody>
</table>
</div>

UsedVehicleSystem/Views/SistemYoneticisi/Giris.cshtml
@if ((@ViewBag?.Hata ?? "").Length > 0)
{
    <div class="alert alert-danger">
        <p>@ViewBag.Hata</p>
    </div>
}

<form id="loginForm" method="post" asp-controller="SistemYoneticisi" asp-action="GirisYap">
    <div class="card">
        <div class="card-header">
            <h2>Giriş Yap</h2>
        </div>
        <div class="card-body">
            <div class="mb-3">
                <label for="loginTakmaAd" class="form-label">Takma Ad</label>
                <input type="text" class="form-control" id="takmaAd" name="takmaAd" placeholder="Takma adinizi girin" required>
            </div>
            <div class="mb-3">
                <label for="loginSifre" class="form-label">Şifre</label>
                <input type="password" class="form-control" id="sifre" name="sifre" placeholder="Şifrenizi girin" required>
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Giriş Yap</button>
        </div>
    </div>
</form>

UsedVehicleSystem/Views/SistemYoneticisi/Home.cshtml
@model SistemYoneticisi

<!--
    <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item active"><a class="nav-link" asp-controller="SistemYoneticisi" asp-action="Home">Home</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="SistemYoneticisi" asp-action="AracMarkaEkle">Marka Ekle</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="SistemYoneticisi" asp-action="AracModelEkle">Model Ekle</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="SistemYoneticisi" asp-action="Ilanlar">İlanlar</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="SistemYoneticisi" asp-action="Araclar">Araçlar</a></li>
                <li class="nav-item"><a class="btn btn-danger" asp-controller="SistemYoneticisi" asp-action="Cikis">Çıkış</a></li>
            </ul>
        </div>
    </nav>
</div>
-->

<h1>Hoş geldiniz @Model.takmaAd </h1>

<div class="text-center">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <div class="d-grid gap-3 mb-3">
                        <a class="nav-link" asp-controller="SistemYoneticisi" asp-action="Home">Ana Sayfa</a>
                        <a class="nav-link" asp-controller="SistemYoneticisi" asp-action="AracMarkaEkle">Marka Ekle</a>
                        <a class="nav-link" asp-controller="SistemYoneticisi" asp-action="AracModelEkle">Model Ekle</a>
                        <a class="nav-link" asp-controller="SistemYoneticisi" asp-action="Ilanlar">İlanlar</a>
                        <a class="nav-link" asp-controller="SistemYoneticisi" asp-action="Araclar">Araçlar</a>
                        <a class="btn btn-danger" asp-controller="SistemYoneticisi" asp-action="Cikis">Çıkış</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

UsedVehicleSystem/Views/SistemYoneticisi/Ilanlar.cshtml
@model List<Ilan>
<div class="card">
    <div class="card-header"><h3 class="title text-center">Onay Bekleyenler</h3></div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Ilan Adı</th>
                    <th scope="col">Ilan Fiyatı</th>
                    <th scope="col">Ilan Durumu</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Ilan ilan in Model)
                {
                    @if(!ilan.onayliMi)
                    {
                        <tr>
                            <td>@ilan.ID</td>
                            <td>@ilan.ilanAdi</td>
                            <td>@ilan.ilanFiyati</td>
                            <td><a class="btn btn-success" href="/SistemYoneticisi/IlanOnayla?ID=@ilan.ID">Onayla</a></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>